---
# tasks file for docker-registry
- name: Pushing
  docker_image:
   name: test
   repository: farahbenmahmoud/myapp
   source: build
   build:         
     path: /var/lib/jenkins/workspace/livraison
   tag: latest
   push: yes
